// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-dNLTZAUPJFtwGZ-Efu_6-QJkM5xULdU',
    appId: '1:1099205068544:web:d5c6d1ce8bf465d619d5e5',
    messagingSenderId: '1099205068544',
    projectId: 'coloristtt-aabc1',
    authDomain: 'coloristtt-aabc1.firebaseapp.com',
    storageBucket: 'coloristtt-aabc1.firebasestorage.app',
    measurementId: 'G-BF26PJW950',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0LVKfN1Uagp081Ps2qLkDezKDbKmkiPI',
    appId: '1:1099205068544:android:b7ab161bc97a724019d5e5',
    messagingSenderId: '1099205068544',
    projectId: 'coloristtt-aabc1',
    storageBucket: 'coloristtt-aabc1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALsFJF1rYOfGeJkwK5F3bjNRTy4i_I5LI',
    appId: '1:1099205068544:ios:da254dbd3a8b9d4c19d5e5',
    messagingSenderId: '1099205068544',
    projectId: 'coloristtt-aabc1',
    storageBucket: 'coloristtt-aabc1.firebasestorage.app',
    iosBundleId: 'com.example.colorist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALsFJF1rYOfGeJkwK5F3bjNRTy4i_I5LI',
    appId: '1:1099205068544:ios:da254dbd3a8b9d4c19d5e5',
    messagingSenderId: '1099205068544',
    projectId: 'coloristtt-aabc1',
    storageBucket: 'coloristtt-aabc1.firebasestorage.app',
    iosBundleId: 'com.example.colorist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-dNLTZAUPJFtwGZ-Efu_6-QJkM5xULdU',
    appId: '1:1099205068544:web:a01c02806e7e152919d5e5',
    messagingSenderId: '1099205068544',
    projectId: 'coloristtt-aabc1',
    authDomain: 'coloristtt-aabc1.firebaseapp.com',
    storageBucket: 'coloristtt-aabc1.firebasestorage.app',
    measurementId: 'G-CN6YY10Z43',
  );
}
